### ISSUE TITLE
IE support ? 

### ISSUE THREAD

**Issue by dixitcy** [FormidableLabs/react-game-kit#13]
The demo doesn't run in IE (checked on IE 11) , it throws an error at this line
https://github.com/FormidableLabs/react-game-kit/blob/master/src/utils/audio-player.js#L10

This seems to be an audioPlayer issue , so does react-game-kit itself run on IE (IE 9 ?) without the audio ?

**Comment by linonetwo** [comment]
Why IE 。。。 Even in china we hate IE

**Comment by dixitc** [comment]
Update on this , it works on IE including IE 9 .
