### ISSUE TITLE
Sprites on react-native

### ISSUE THREAD

**Issue by timCF** [FormidableLabs/react-game-kit#20]
Why here is a number type?

https://github.com/FormidableLabs/react-game-kit/blob/18b57bfe51b4c85b0b0721e2866fccc8216fa0f2/src/native/components/sprite.js#L12

**Comment by itsjef** [comment]
Why did you close this issue? Did you find an answer or something, please explain?

**Comment by timCF** [comment]
Number type here is good here, because expressions like
```javascript
require("./myimg.png")
```
have Number type :)

**Comment by itsjef** [comment]
Works for me. Many thanks :+1:
