### ISSUE TITLE
Bodies are positioned relative to their center points

### ISSUE THREAD

**Issue by JeffreyATW** [FormidableLabs/react-game-kit#3]
I just put together a simple game to test the library:
https://github.com/JeffreyATW/react-redux-platformer

I noticed that the collision was off when I first placed bodies in the world, and only noticed later that it was because I was treating their coordinates as originating from the upper left, while Matter.js was treating them from their center.

I have to position elements and factor in their widths and heights, which seems like overkill:

``` js
{
  transform: `translate(${(targetX - this.width / 2) * scale}px, ${(y - this.height / 2) * scale}px)`
}
```

I'm currently not using the `Sprite` class, so I don't know if that would somehow solve the problem, but I'm wondering if there's a simple way of reconciling the differences in origin points. Is there some sort of setting I can pass to Matter.js, or some easier way to store their coordinates that I'm not thinking of?

**Comment by kenwheeler** [comment]
Nope. Do you think I should bake in top left translation?
