### ISSUE TITLE
Multiplayer games?

### ISSUE THREAD

**Issue by Jonovono** [FormidableLabs/react-game-kit#36]
Hi. I am new to game dev and want to explore the crazy world of making a multiplayer game.

I've been looking at like pixi, phaser Game Maker etc. 

I just came across this project and it seems like it would fit into our existing app very nicely since it's a react native app we are making. 

However, has anyone tried introducing multiplayer into it yet? Any ideas how that would work? We arn't making very complex games. Think stuff like tic tac toe for now.

**Comment by michaellee8** [comment]
I am not an game developer, but I think that the multiplayer layer is just a network problem. There are tutorial online about how to develop a multiplayer game. I believe your may want some lower level library like socket.io or higher level solutions like firebase.
I think this library is not in that scope. This is just some helper functions for client side game logic implementation, physics and rendering.
And for complex games, there are better library than this one. Check out pharser.js for 2D or unreal engine/unity for 3d. Yet web games are not so good in performance when you are make it complex. You will want some native solution when it's lagging.

**Comment by michaellee8** [comment]
https://www.sitepoint.com/building-a-game-reactjs-and-webgl/
Maybe you would like to checkout this one as well.

**Comment by jstoeffler** [comment]
This library is more a client-side/rendering library.

I'm sure you can use it to create multiplayer games, but it won't solve anything related to multiplayer games.

There are many multiplayer games solutions out there, I suggest you take a look at https://github.com/gamestdio/colyseus (it has a "tic-tac-toe" example by the way).

I guess this issue should be closed, as it's not related to the development of the react game kit library.
