### ISSUE TITLE
Use PropTypes from external package

### ISSUE THREAD

**Issue by webpty** [FormidableLabs/react-game-kit#37]
Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. 
Use the latest available v15.* prop-types package from npm instead. 
For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

**Comment by ryan-roemer** [comment]
Fixed in https://github.com/FormidableLabs/react-game-kit/pull/38
