### ISSUE TITLE
React 16 - No longer have React.PropTypes

### ISSUE THREAD

**Issue by larspa** [FormidableLabs/react-game-kit#39]
If people want to update their project to React 16 they can no longer use your package as you use React.PropTypes which is completely being removed by Facebook.
Instead you have to use their package [https://github.com/facebook/prop-types](https://github.com/facebook/prop-types)

**Comment by ryan-roemer** [comment]
Fixed in https://github.com/FormidableLabs/react-game-kit/pull/38
