### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded at Stage.__setDimensions__REACT_HOT_LOADER__

### ISSUE THREAD

**Issue by MKoth** [FormidableLabs/react-game-kit#48]
I've even downloaded the src example and compiled everything locally, it showed me the same error when I setting <Stage> component. I guess some package has been updated and that caused the issue

**Comment by ryan-roemer** [comment]
Can you create a minimal repository with install + error reproduction steps so we can more easily jump in and diagnose the issue? Thanks!

**Comment by MKoth** [comment]
Ok, here, for example
https://github.com/MKoth/game-kit-example

**Comment by MKoth** [comment]
Please, let me know if I'm doins something wrong.

**Comment by ryan-roemer** [comment]
Thanks for the repository @MKoth ! Can you also provide install + error reproduction steps?

**Comment by MKoth** [comment]
Run the commands:
npm install
npm run start

**Comment by MKoth** [comment]
You'll see the error on the localhost console

**Comment by MKoth** [comment]
I've updated the git repository, previous contained som non related error

**Comment by MKoth** [comment]
Interesting, thing, I've dowgraded to 1.0.0 version, there's no errors

**Comment by ryan-roemer** [comment]
I think it might be related to `"react-hot-loader/babel"` being in what we *publish* which doesn't seem right.

/cc @stefvhuynh @kenwheeler

**Comment by ryan-roemer** [comment]
WIP branch at: https://github.com/FormidableLabs/react-game-kit/compare/bug/react-hot-loader

**Comment by ryan-roemer** [comment]
I believe it is this issue: https://github.com/gaearon/react-hot-loader/issues/698

I'm converting our arrow funcs to real funcs.
