### ISSUE TITLE
Do you have any related document

### ISSUE THREAD

**Issue by yll2wcf** [FormidableLabs/react-game-kit#5]
Do you have any related document

**Comment by kenwheeler** [comment]
For what?

**Comment by mraak** [comment]
Maybe @yll2wcf means general documentation for the API for this kit.

**Comment by kenwheeler** [comment]
@mraak @yll2wcf https://github.com/FormidableLabs/react-game-kit#api ?

**Comment by yll2wcf** [comment]
Thank you, I'm ready to learn, in fact my English is not good, forgive me
