### ISSUE TITLE
I am starting for game developing with using react-game-kit

### ISSUE THREAD

**Issue by kjin9174** [FormidableLabs/react-game-kit#51]
I tried myself. But it is not working. I gonna make image animation first.
I run localhost:3000
I have already created app: okan
So i got react static screen by localhost:3000
I wanna use demo and samples of https://github.com/FormidableLabs/react-game-kit by customizing okan/src/app.js
   my first example code is below
   import React, { Component } from 'react';
import { Loop, Stage,World, Body, MySprite } from 'react-game-kit';
import ReactDOM from 'react-dom';
import PropTypes from 'prop-types';

class Game extends Component {
  render() {
    return (
      <Body
        args={[0, 384, 64, 64, { inertia: Infinity }]}
        ref={(b) => { this.body = b; }}
      >
        <MySprite/>
      </Body>
    );
  }
}

export default Game;

but this is error
TypeError: Cannot read property 'world' of undefined
new Body
C:/Program Files/nodejs/node_modules/react-game-kit/lib/components/body.js:48
  45 |       options = _objectWithoutProperties(props, ['args', 'children', 'shape']); // eslint-disable-line no-unused-vars
  46 | 
  47 |   _this.body = _matterJs.Bodies[shape].apply(_matterJs.Bodies, _toConsumableArray(args).concat([options]));
> 48 |   _matterJs.World.addBody(context.engine.world, _this.body);
  49 |   return _this;
  50 | }
  51 | 
View compiled
constructClassInstance
C:/Program Files/nodejs/okan/node_modules/react-dom/cjs/react-dom.development.js:6355
  6352 | var unmaskedContext = getUnmaskedContext(workInProgress);
  6353 | var needsContext = isContextConsumer(workInProgress);
  6354 | var context = needsContext ? getMaskedContext(workInProgress, unmaskedContext) : emptyObject;
> 6355 | var instance = new ctor(props, context);
  6356 | adoptClassInstance(workInProgress, instance);
  6357 | 
  6358 | // Cache unmasked context so we can avoid recreating masked context unless necessary.
View compiled
updateClassComponent
C:/Program Files/nodejs/okan/node_modules/react-dom/cjs/react-dom.development.js:7839
  7836 | if (current === null) {
........................

It seems like that i don't know method that use tags of react-game-kit package
If react-game-kit tags is working in my app.js, then i want to build for displaying my hosting webserver.
But i don't know well cause i am amateur.
Thanks for your advise.

**Comment by katzmannn** [comment]
@kjin9174 your body has to be inside of loop and stage and world. You should read the documentation in the readme

**Comment by kjin9174** [comment]
thanks, Could you write code for very simple animation here,sir?
I don't understand, sorry.
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import logo from './logo.svg';
import intro from './assets/intro.png';
import './App.css';
import { Loop, Stage, World, Body } from 'react-game-kit';
import PropTypes from 'prop-types';
import{ AudioPlayer} from 'react-game-kit';


export default class Intro extends Component {
  static propTypes = {
    onStart: PropTypes.func,
  };

  constructor(props) {
    super(props);

    this.state = {
      blink: false,
    };

    this.startUpdate = this.startUpdate.bind(this);
    this.handleKeyPress = this.handleKeyPress.bind(this);
  }

  componentDidMount() {
    this.startNoise = new AudioPlayer('/assets/start.wav');
    window.addEventListener('keypress', this.handleKeyPress);
    this.animationFrame = requestAnimationFrame(this.startUpdate);
    this.interval = setInterval(() => {
      this.setState({
        blink: !this.state.blink,
      });
    }, 500);
  }

  componentWillUnmount() {
    window.removeEventListener('keypress', this.handleKeyPress);
    cancelAnimationFrame(this.animationFrame);
    clearInterval(this.interval);
  }

  render() {
    return (
      <div>
        <img className="intro" src={intro} />
        <p
          className="start"
          style={{ display: this.state.blink ? 'block' : 'none' }}
        >
          Press Start
        </p>
      </div>
    );
  }

  startUpdate() {
    this.animationFrame = requestAnimationFrame(this.startUpdate);
  }

  handleKeyPress(e) {
    if (e.keyCode === 13) {
      this.startNoise.play();
      this.props.onStart();
    }
  }
}

this code is working

But what import code should i use for using <Sprite> tags in react-game-kit?????

**Comment by katzmannn** [comment]
[Read this in order to better understand how this library works](https://github.com/FormidableLabs/react-game-kit/blob/master/README.md)

**Comment by kjin9174** [comment]
I've already read it.
But i don't understand,sir. sorry.
Could you send here for simple animation code to me?

**Comment by katzmannn** [comment]
what do you need to animate?

**Comment by kjin9174** [comment]
right going and left going animation,sir

**Comment by kjin9174** [comment]
with using <Sprite>
How should i import?
import { Loop, Stage, ...etc } from 'react-game-kit/native'; is not working in my end. error is coming
help me,sir

**Comment by kjin9174** [comment]
i need your code of this format.sir
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import logo from './logo.svg';
import intro from './assets/intro.png';
import './App.css';
import { Loop, Stage, World, Body } from 'react-game-kit';
import PropTypes from 'prop-types';
import{ AudioPlayer} from 'react-game-kit';


export default class Intro extends Component {
  static propTypes = {
    onStart: PropTypes.func,
  };

  constructor(props) {
    super(props);

    this.state = {
      blink: false,
    };

    this.startUpdate = this.startUpdate.bind(this);
    this.handleKeyPress = this.handleKeyPress.bind(this);
  }

  componentDidMount() {
    
    window.addEventListener('keypress', this.handleKeyPress);
    this.animationFrame = requestAnimationFrame(this.startUpdate);
    this.interval = setInterval(() => {
      this.setState({
        blink: !this.state.blink,
      });
    }, 500);
  }

  componentWillUnmount() {
    window.removeEventListener('keypress', this.handleKeyPress);
    cancelAnimationFrame(this.animationFrame);
    clearInterval(this.interval);
  }

  render() {
    return (
      <div>
        <img className="intro" src={intro} style={{height:500, width:800}}/>
        <p
          className="start"
          style={{ display: this.state.blink ? 'block' : 'none' }}
        >
          Press Start
        </p>
      </div>
    );
  }

  startUpdate() {
    this.animationFrame = requestAnimationFrame(this.startUpdate);
  }

  handleKeyPress(e) {
    if (e.keyCode === 13) {
            
    }
  }
}

**Comment by katzmannn** [comment]
what are you animating?

**Comment by kjin9174** [comment]
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import logo from './logo.svg';
import intro from './assets/intro.png';
import './App.css';
import { Loop, Stage, World, Body, Sprite } from 'react-game-kit';
import PropTypes from 'prop-types';
import{ AudioPlayer} from 'react-game-kit';


class App extends Component {
  static contextTypes = {
    loop: PropTypes.object,
  };

  loop = () => {
    //Do stuff here
  };

  componentDidMount() {
    this.loopID = this.context.loop.subscribe(this.loop);
  }

  componentWillUnmount() {
    this.context.loop.unsubscribe(this.loopID);
  }

	render() {
    return (
  <Sprite
    repeat={true}
    src="./assets/intro.png"
    scale={this.context.scale * 2}
    state={0}
    steps={[9, 9, 0, 4, 5]}
  />
);
  }
}

export default App;






this is my code of app.js of my new react app. but it is not working.
so i need to know how i should fix.

**Comment by ryan-roemer** [comment]
Closing as we don't have a specific issue here, and it's been a while :)
