### ISSUE TITLE
Performance without canvas?

### ISSUE THREAD

**Issue by mattcolman** [FormidableLabs/react-game-kit#7]
Hey! This looks super cool, because React is cool and games are cool...but can this really achieve 60fps without the use of canvas? I assume spawning lots of particles will cause some jank?
Thanks.

**Comment by kenwheeler** [comment]
Everything I've tried hits 60fps. I have a canvas branch I'll push if you want. Doesn't perform quite as well.

**Comment by mattcolman** [comment]
cool, yeah I'd be interested to see the canvas branch. Thanks!
