### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by DanielRuf** [FormidableLabs/react-game-kit#77]
Hi, what is the current status of this project? Is it still actively maintained?

**Comment by josiahbryan** [comment]
Wondering the same...?

**Comment by RWOverdijk** [comment]
From the README:

> Maintenance Status
Archived: This project is no longer maintained by Formidable. We are no longer responding to issues or pull requests unless they relate to security concerns. We encourage interested developers to fork this project and make it their own!

**Comment by DanielRuf** [comment]
Was not so long ago ;-)

https://github.com/FormidableLabs/react-game-kit/commit/8a657294d2d1622e020f1bc671f4606b82eb1e0b

**Comment by DanielRuf** [comment]
Very unfortunate that they do not work on this anymore.
